version: "3.9"
services:
  ros2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ros2_humble_full
    volumes:
      - ../ros_ws:/ros_ws
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev:/dev
    stdin_open: true
    tty: true
